// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.zhb.file.proto;

/**protobuf
 **简便、高校、兼容性
 **用于存储结构化数据以及rpc数据交换
 **二进制数据传输格式
 **varint编码后的消息的内容小，适于网络传输
*/
public final class FileProtos {
  private FileProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:File)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string key = 2;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 2;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 3;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 3;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code File}
   */
  public  static final class File extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:File)
      FileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use File.newBuilder() to construct.
    private File(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private File() {
      id_ = 0;
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private File(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhb.file.proto.FileProtos.internal_static_File_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhb.file.proto.FileProtos.internal_static_File_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhb.file.proto.FileProtos.File.class, com.zhb.file.proto.FileProtos.File.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 2;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 3;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhb.file.proto.FileProtos.File)) {
        return super.equals(obj);
      }
      com.zhb.file.proto.FileProtos.File other = (com.zhb.file.proto.FileProtos.File) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getKey()
          .equals(other.getKey());
      result = result && getValue()
          .equals(other.getValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhb.file.proto.FileProtos.File parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.File parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhb.file.proto.FileProtos.File parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhb.file.proto.FileProtos.File parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhb.file.proto.FileProtos.File prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code File}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:File)
        com.zhb.file.proto.FileProtos.FileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhb.file.proto.FileProtos.internal_static_File_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhb.file.proto.FileProtos.internal_static_File_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhb.file.proto.FileProtos.File.class, com.zhb.file.proto.FileProtos.File.Builder.class);
      }

      // Construct using com.zhb.file.proto.FileProtos.File.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        key_ = "";

        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhb.file.proto.FileProtos.internal_static_File_descriptor;
      }

      @java.lang.Override
      public com.zhb.file.proto.FileProtos.File getDefaultInstanceForType() {
        return com.zhb.file.proto.FileProtos.File.getDefaultInstance();
      }

      @java.lang.Override
      public com.zhb.file.proto.FileProtos.File build() {
        com.zhb.file.proto.FileProtos.File result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zhb.file.proto.FileProtos.File buildPartial() {
        com.zhb.file.proto.FileProtos.File result = new com.zhb.file.proto.FileProtos.File(this);
        result.id_ = id_;
        result.key_ = key_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhb.file.proto.FileProtos.File) {
          return mergeFrom((com.zhb.file.proto.FileProtos.File)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhb.file.proto.FileProtos.File other) {
        if (other == com.zhb.file.proto.FileProtos.File.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhb.file.proto.FileProtos.File parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhb.file.proto.FileProtos.File) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 2;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 3;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 3;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 3;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:File)
    }

    // @@protoc_insertion_point(class_scope:File)
    private static final com.zhb.file.proto.FileProtos.File DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhb.file.proto.FileProtos.File();
    }

    public static com.zhb.file.proto.FileProtos.File getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<File>
        PARSER = new com.google.protobuf.AbstractParser<File>() {
      @java.lang.Override
      public File parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new File(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<File> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<File> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zhb.file.proto.FileProtos.File getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .File fileList = 1;</code>
     */
    java.util.List<com.zhb.file.proto.FileProtos.File> 
        getFileListList();
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    com.zhb.file.proto.FileProtos.File getFileList(int index);
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    int getFileListCount();
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    java.util.List<? extends com.zhb.file.proto.FileProtos.FileOrBuilder> 
        getFileListOrBuilderList();
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    com.zhb.file.proto.FileProtos.FileOrBuilder getFileListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code FileList}
   */
  public  static final class FileList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileList)
      FileListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileList.newBuilder() to construct.
    private FileList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileList() {
      fileList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                fileList_ = new java.util.ArrayList<com.zhb.file.proto.FileProtos.File>();
                mutable_bitField0_ |= 0x00000001;
              }
              fileList_.add(
                  input.readMessage(com.zhb.file.proto.FileProtos.File.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          fileList_ = java.util.Collections.unmodifiableList(fileList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhb.file.proto.FileProtos.internal_static_FileList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhb.file.proto.FileProtos.internal_static_FileList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhb.file.proto.FileProtos.FileList.class, com.zhb.file.proto.FileProtos.FileList.Builder.class);
    }

    public static final int FILELIST_FIELD_NUMBER = 1;
    private java.util.List<com.zhb.file.proto.FileProtos.File> fileList_;
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    public java.util.List<com.zhb.file.proto.FileProtos.File> getFileListList() {
      return fileList_;
    }
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    public java.util.List<? extends com.zhb.file.proto.FileProtos.FileOrBuilder> 
        getFileListOrBuilderList() {
      return fileList_;
    }
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    public int getFileListCount() {
      return fileList_.size();
    }
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    public com.zhb.file.proto.FileProtos.File getFileList(int index) {
      return fileList_.get(index);
    }
    /**
     * <code>repeated .File fileList = 1;</code>
     */
    public com.zhb.file.proto.FileProtos.FileOrBuilder getFileListOrBuilder(
        int index) {
      return fileList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < fileList_.size(); i++) {
        output.writeMessage(1, fileList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < fileList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fileList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhb.file.proto.FileProtos.FileList)) {
        return super.equals(obj);
      }
      com.zhb.file.proto.FileProtos.FileList other = (com.zhb.file.proto.FileProtos.FileList) obj;

      boolean result = true;
      result = result && getFileListList()
          .equals(other.getFileListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFileListCount() > 0) {
        hash = (37 * hash) + FILELIST_FIELD_NUMBER;
        hash = (53 * hash) + getFileListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhb.file.proto.FileProtos.FileList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhb.file.proto.FileProtos.FileList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhb.file.proto.FileProtos.FileList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileList)
        com.zhb.file.proto.FileProtos.FileListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhb.file.proto.FileProtos.internal_static_FileList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhb.file.proto.FileProtos.internal_static_FileList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhb.file.proto.FileProtos.FileList.class, com.zhb.file.proto.FileProtos.FileList.Builder.class);
      }

      // Construct using com.zhb.file.proto.FileProtos.FileList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFileListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fileListBuilder_ == null) {
          fileList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          fileListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhb.file.proto.FileProtos.internal_static_FileList_descriptor;
      }

      @java.lang.Override
      public com.zhb.file.proto.FileProtos.FileList getDefaultInstanceForType() {
        return com.zhb.file.proto.FileProtos.FileList.getDefaultInstance();
      }

      @java.lang.Override
      public com.zhb.file.proto.FileProtos.FileList build() {
        com.zhb.file.proto.FileProtos.FileList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zhb.file.proto.FileProtos.FileList buildPartial() {
        com.zhb.file.proto.FileProtos.FileList result = new com.zhb.file.proto.FileProtos.FileList(this);
        int from_bitField0_ = bitField0_;
        if (fileListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            fileList_ = java.util.Collections.unmodifiableList(fileList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.fileList_ = fileList_;
        } else {
          result.fileList_ = fileListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhb.file.proto.FileProtos.FileList) {
          return mergeFrom((com.zhb.file.proto.FileProtos.FileList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhb.file.proto.FileProtos.FileList other) {
        if (other == com.zhb.file.proto.FileProtos.FileList.getDefaultInstance()) return this;
        if (fileListBuilder_ == null) {
          if (!other.fileList_.isEmpty()) {
            if (fileList_.isEmpty()) {
              fileList_ = other.fileList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFileListIsMutable();
              fileList_.addAll(other.fileList_);
            }
            onChanged();
          }
        } else {
          if (!other.fileList_.isEmpty()) {
            if (fileListBuilder_.isEmpty()) {
              fileListBuilder_.dispose();
              fileListBuilder_ = null;
              fileList_ = other.fileList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fileListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFileListFieldBuilder() : null;
            } else {
              fileListBuilder_.addAllMessages(other.fileList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhb.file.proto.FileProtos.FileList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhb.file.proto.FileProtos.FileList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zhb.file.proto.FileProtos.File> fileList_ =
        java.util.Collections.emptyList();
      private void ensureFileListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          fileList_ = new java.util.ArrayList<com.zhb.file.proto.FileProtos.File>(fileList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zhb.file.proto.FileProtos.File, com.zhb.file.proto.FileProtos.File.Builder, com.zhb.file.proto.FileProtos.FileOrBuilder> fileListBuilder_;

      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public java.util.List<com.zhb.file.proto.FileProtos.File> getFileListList() {
        if (fileListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fileList_);
        } else {
          return fileListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public int getFileListCount() {
        if (fileListBuilder_ == null) {
          return fileList_.size();
        } else {
          return fileListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public com.zhb.file.proto.FileProtos.File getFileList(int index) {
        if (fileListBuilder_ == null) {
          return fileList_.get(index);
        } else {
          return fileListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder setFileList(
          int index, com.zhb.file.proto.FileProtos.File value) {
        if (fileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileListIsMutable();
          fileList_.set(index, value);
          onChanged();
        } else {
          fileListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder setFileList(
          int index, com.zhb.file.proto.FileProtos.File.Builder builderForValue) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          fileList_.set(index, builderForValue.build());
          onChanged();
        } else {
          fileListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder addFileList(com.zhb.file.proto.FileProtos.File value) {
        if (fileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileListIsMutable();
          fileList_.add(value);
          onChanged();
        } else {
          fileListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder addFileList(
          int index, com.zhb.file.proto.FileProtos.File value) {
        if (fileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileListIsMutable();
          fileList_.add(index, value);
          onChanged();
        } else {
          fileListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder addFileList(
          com.zhb.file.proto.FileProtos.File.Builder builderForValue) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          fileList_.add(builderForValue.build());
          onChanged();
        } else {
          fileListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder addFileList(
          int index, com.zhb.file.proto.FileProtos.File.Builder builderForValue) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          fileList_.add(index, builderForValue.build());
          onChanged();
        } else {
          fileListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder addAllFileList(
          java.lang.Iterable<? extends com.zhb.file.proto.FileProtos.File> values) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fileList_);
          onChanged();
        } else {
          fileListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder clearFileList() {
        if (fileListBuilder_ == null) {
          fileList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fileListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public Builder removeFileList(int index) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          fileList_.remove(index);
          onChanged();
        } else {
          fileListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public com.zhb.file.proto.FileProtos.File.Builder getFileListBuilder(
          int index) {
        return getFileListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public com.zhb.file.proto.FileProtos.FileOrBuilder getFileListOrBuilder(
          int index) {
        if (fileListBuilder_ == null) {
          return fileList_.get(index);  } else {
          return fileListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public java.util.List<? extends com.zhb.file.proto.FileProtos.FileOrBuilder> 
           getFileListOrBuilderList() {
        if (fileListBuilder_ != null) {
          return fileListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fileList_);
        }
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public com.zhb.file.proto.FileProtos.File.Builder addFileListBuilder() {
        return getFileListFieldBuilder().addBuilder(
            com.zhb.file.proto.FileProtos.File.getDefaultInstance());
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public com.zhb.file.proto.FileProtos.File.Builder addFileListBuilder(
          int index) {
        return getFileListFieldBuilder().addBuilder(
            index, com.zhb.file.proto.FileProtos.File.getDefaultInstance());
      }
      /**
       * <code>repeated .File fileList = 1;</code>
       */
      public java.util.List<com.zhb.file.proto.FileProtos.File.Builder> 
           getFileListBuilderList() {
        return getFileListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zhb.file.proto.FileProtos.File, com.zhb.file.proto.FileProtos.File.Builder, com.zhb.file.proto.FileProtos.FileOrBuilder> 
          getFileListFieldBuilder() {
        if (fileListBuilder_ == null) {
          fileListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zhb.file.proto.FileProtos.File, com.zhb.file.proto.FileProtos.File.Builder, com.zhb.file.proto.FileProtos.FileOrBuilder>(
                  fileList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          fileList_ = null;
        }
        return fileListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileList)
    }

    // @@protoc_insertion_point(class_scope:FileList)
    private static final com.zhb.file.proto.FileProtos.FileList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhb.file.proto.FileProtos.FileList();
    }

    public static com.zhb.file.proto.FileProtos.FileList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileList>
        PARSER = new com.google.protobuf.AbstractParser<FileList>() {
      @java.lang.Override
      public FileList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zhb.file.proto.FileProtos.FileList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_File_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_File_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\".\n\004File\022\n\n\002id\030\001 \001(\005\022\013\n\003key\030" +
      "\002 \001(\t\022\r\n\005value\030\003 \001(\t\"#\n\010FileList\022\027\n\010file" +
      "List\030\001 \003(\0132\005.FileB \n\022com.zhb.file.protoB" +
      "\nFileProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_File_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_File_descriptor,
        new java.lang.String[] { "Id", "Key", "Value", });
    internal_static_FileList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileList_descriptor,
        new java.lang.String[] { "FileList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
